/*
 * Copyright (c) 2022, FusionAuth, All Rights Reserved
 */
package io.fusionauth.domain;

import com.inversoft.json.JacksonConstructor;
import io.fusionauth.domain.api.webauthn.enums.AuthenticatorTransport;
import io.fusionauth.domain.api.webauthn.enums.CoseAlgorithmIdentifier;
import io.fusionauth.domain.internal._InternalJSONColumn;
import io.fusionauth.domain.internal.annotation.InternalJSONColumn;

import java.time.ZonedDateTime;
import java.util.*;

/**
 * A User's WebAuthnCredential. Contains all data required to complete WebAuthn authentication ceremonies.
 *
 * @author Spencer Witt
 */
public class WebAuthnCredential implements Buildable<WebAuthnCredential>, _InternalJSONColumn {
  /**
   * The signature algorithm used with the key
   */
  @InternalJSONColumn
  public CoseAlgorithmIdentifier alg;

  /**
   * The credential ID generated by the <i>authenticator</i> stored as a base64URL-encoded String
   */
  public String credentialId;

  public Map<String, Object> data = new LinkedHashMap<>();

  public UUID id;

  public ZonedDateTime insertInstant;

  public ZonedDateTime lastUseInstant;

  /**
   * The public key encoded in PEM format
   */
  @InternalJSONColumn
  public String publicKey;

  /**
   * The number of signatures generated with the key
   */
  @InternalJSONColumn
  public int signCount;

  public UUID tenantId;

  /**
   * A list of transport types supported by the WebAuthn <i>authenticator</i> that generated the key
   */
  @InternalJSONColumn
  public List<AuthenticatorTransport> transports = new ArrayList<>();

  public UUID userId;

  @JacksonConstructor
  public WebAuthnCredential() {
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    WebAuthnCredential that = (WebAuthnCredential) o;
    return signCount == that.signCount && alg == that.alg && credentialId.equals(that.credentialId) && id.equals(that.id) && insertInstant.equals(that.insertInstant) && lastUseInstant.equals(that.lastUseInstant) && publicKey.equals(that.publicKey) && tenantId.equals(that.tenantId) && transports.equals(that.transports) && userId.equals(that.userId);
  }

  @Override
  public int hashCode() {
    return Objects.hash(alg, credentialId, id, insertInstant, lastUseInstant, publicKey, signCount, tenantId, transports, userId);
  }
}
